---
# tasks file for nginx_proxy

- name: Установка nginx
  apt:
    name: "nginx"
    state: present

- name: Подмена конфига nginx
  copy:
    src: "yandex_proxy"
    dest: "/etc/nginx/sites-enabled/default"
  notify: "Nginx Reloader"
